name: gcn-gpu
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9.7
  - pip=21.2.4
  - cudatoolkit=11.3.1
  - pytorch=1.10.0
  - torchvision=0.11.1
  - numpy==1.22
  - matplotlib==3.5.1
  - scipy==1.7.3
  - pandas==1.3.5
  - pip:
    - tqdm==4.62.3
    - repackage==0.7.3
    - yacs==0.1.8
